### ISSUE TITLE
Charts old versions

### ISSUE THREAD

**Issue by lumi017** [google-cloud-tools/kube-eagle-helm-chart#13]
Is it possible to keep old versions of helm charts packages? I am relying on a specific version for the installation, but it breaks once you override it with a new version. Any plans to move to charts/stable?

**Comment by weeco** [comment]
I believe all the new chart versions are backwards compatible, aren't they? I planned to keep the latest version of each major version.

There are no plans to move the chart to charts/stable because of two reasons:
1. I do not believe they would add charts for unpopular applications such as Kube Eagle
2. I do not like being dependent on the Helm chart members to get changes merged into stable. Just recently I contributed to a SSO chart and it took 6 months until a chart member reviewed and merged it.

**Comment by lumi017** [comment]
IMO, it's a good practice to keep versioning. You can easily achieve it by making releases. It will create a tag with a snapshot of your repo including the chart package. You can also add release notes to it.

**Comment by lumi017** [comment]
Have a look at https://github.com/mumoshu/prometheus-process-exporter He does the release and attaches the package tgz to it and the index.yaml points to the download of the tgz from each release
https://github.com/mumoshu/prometheus-process-exporter/releases
https://github.com/mumoshu/prometheus-process-exporter/blob/master/docs/index.yaml#L21

**Comment by weeco** [comment]
I already did it for the last release or am I missing something?

**Comment by lumi017** [comment]
Yeah, just wanted to share a nice pattern which leverages the release feature of github

**Comment by weeco** [comment]
Ah now I get your point. This way all the packages do not pollute the repository which is nice. I am just wondering how he gets the packages into the releases. Does he upload the files as github release manually on each release or is there a better way?

**Comment by lumi017** [comment]
There are some tools to automate it. For example https://github.com/cheton/github-release-cli
