### ISSUE TITLE
Support for k8s 1.16

### ISSUE THREAD

**Issue by radut** [google-cloud-tools/kube-eagle-helm-chart#21]
K8s 1.16 has removed deprecated versions of api's.
Do you have any plan to make it work for 1.16 too ?

* https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

```
helm install --name=kube-eagle kube-eagle/kube-eagle

Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"
```

**Comment by weeco** [comment]
Hey @radut ,
thank you for submitting the issue and the pullrequest. Yes of course I'd like to make it work for v1.16+ too. Currently I hesitate to merge it because I am not sure what api versions are supported by each Kubernetes version.

I couldn't find an overview which shows show the supported/deprecated API versions for each Kubernetes version. Are you aware of one? I'd just like to double check we don't break backwards compatibility for Kubernetes versions which are reasonably "up to date" (the GKE, EKS etc. versions usually lag behind, and people might not use the latest GKE version).

**Comment by radut** [comment]
I would at least make it as beta version, installable from helm repo....
I'm not sure how it works..
but for example right now I installed from github repo cloned locally. If it would be possible to specify from charts/ version.. which to pull maybe we cover this switch for the moment.

later on switch .16 to default.. and to install on older versions specify the helm template version manually.

**Comment by weeco** [comment]
Resolved with https://github.com/cloudworkz/kube-eagle-helm-chart/pull/22
